name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - master

env:
  ACR_SERVER: ${{ secrets.ACR_SERVER }}
  AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./MyTrackStackAPI/Dockerfile
        push: true
        tags: ${{ secrets.ACR_SERVER }}/mytrackstack-api:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        images: ${{ secrets.ACR_SERVER }}/mytrackstack-api:latest
