# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MyTrackStack-API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://mytrackstackregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_99661bd599854885964d7874feccfc01 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_8b9ef9583e5747f2a52e24ef8cc5dc9b }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mytrackstackregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_99661bd599854885964d7874feccfc01 }}/mytrackstackregistry.azurecr.io/MyTrackStack:latest:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'MyTrackStack-API'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_7af3718de47f4f8992945263a726ccbf }}
            images: 'mytrackstackregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_99661bd599854885964d7874feccfc01 }}/mytrackstackregistry.azurecr.io/MyTrackStack:latest:${{ github.sha }}'
