name: Build and Deploy Docker App to Azure Web App

on:
  push:
    branches:
      - main  # or your deployment branch

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: mytrackstackregistry
  IMAGE_NAME: mytrackstack-api
  AZURE_WEBAPP_NAME: mytrackstack-api
  DOCKER_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} .

    - name: Login to ACR
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Push Docker image to ACR
      run: |
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

    - name: Deploy to Azure Web App (Container)
      run: |
        az webapp config container set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group MyTrackStackRG \
          --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} \
          --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io
