name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write     # Required for OIDC token request
  contents: read      # Default for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Build Docker image
        run: |
          docker build -t myacr.azurecr.io/myapp:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: |
          echo ${{ secrets.AZURE_CLIENT_ID }} | docker login myacr.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin
          docker push myacr.azurecr.io/myapp:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-webapp-name
          images: myacr.azurecr.io/myapp:${{ github.sha }}
